version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.1.2
    working_directory: ~/discogs-messenger/api
    steps:
      - checkout:
          path: ~/discogs-messenger
      - run: npm i
      - run: npm run lint
      - run: npm test